spring.datasource.url=jdbc:mysql://localhost:3307/studenti?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Batman@01


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
